#TODO add ref. here
version: '2.0'

services:
  postgres:
    image: mdillon/postgis  # postgres image with postgis ready
    ports:
      - "54322:5432"  # note we double the last digit 2 on purpose to create our port - we aim not to overwrite the original port
    container_name: bxd_postgres
    volumes:
      - v_postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: always

volumes:
  v_postgres:
    driver: local

networks:
  postgres:
    driver: bridge
